# action.yaml
name: "redhat-codeready-dependency-analysis"
description: "The RedHat-CodeReady-Dependency-Analysis action provides vulnerability analysis of application dependencies."
author: 'Red Hat'
branding:
  icon: shield
  color: red

inputs:
  manifest-file-path:
    description: Path of target manifest file to perform analysis.
    required: true
    default: requirements.txt
  output-file-path:
    description: Path of the file to save analysis report.
    required: true
    default: redhat-codeready-dependency-analysis-report.json
  pkg-installation-directory-path:
    description: Path of a directory in workspace, where dependencies are installed.
    required: true
    default: site-dir
runs:
  using: "docker"
  image: 'docker:quay.io/jparsai/crdaimagev6:latest'
  args:
    - '${{ inputs.manifest-file-path}}' 
    - '${{ inputs.output-file-path}}' 
    - '${{ inputs.pkg-installation-directory-path}}'
  entrypoint: '/crda.sh'
