# action.yaml
name: "crda-analysis"
description: "The CRDA Analysis action is an interface to Red Hat CodeReady Dependency Analytics platform. It provides vulnerability and compliance analysis for your applications dependencies, along with recommendations to address security vulnerabilities and licensing issues."

inputs:
  manifest-file-path:
    description: Path of target manifest file to perform analysis.
    required: true
    default: requirements1.txt
  output-file-path:
    description: Path of the file to save analysis report.
    required: true
    default: crda-analysis-report.json
  pkg-installation-directory-path:
    description: Path of a directory in workspace, where dependencies are installed.
    required: true
    default: site-dir
runs:
  using: "docker"
  image: 'docker://ghcr.io/fabric8-analytics/crda-python:3.7'
  args:
    - '${{ inputs.manifest-file-path}}' 
    - '${{ inputs.output-file-path}}' 
    - '${{ inputs.pkg-installation-directory-path}}'
  entrypoint: '/crda.sh'
